apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: controlplane-fwd
resources:
- ./namespace.yaml
- ./ingress.yaml
- ./deployment.yaml

configMapGenerator:
- name: nginx-conf
  files:
  - nginx.conf