- name: install brew
  shell: |
    mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/main | tar xz --strip-components 1 -C homebrew
    echo >> /home/tanut/.bashrc
    echo 'eval "$(/home/tanut/homebrew/bin/brew shellenv)"' >> /home/tanut/.bashrc
    eval "$(/home/tanut/homebrew/bin/brew shellenv)"

- name: Create Homebrew directory
  ansible.builtin.file:
    path: "/home/linuxbrew/.linuxbrew"
    state: directory
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0755'
  become: true

- name: Install Homebrew
  ansible.builtin.shell: |
    curl -fsSL https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C /home/linuxbrew/.linuxbrew
    
- name: install gcc
  shell: |
    sudo apt update && sudo apt install -y gcc
  become: true

- name: install k9s
  shell: |
    /home/tanut/homebrew/bin/brew install derailed/k9s/k9s