- name: install brew
  shell: |
    mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/main | tar xz --strip-components 1 -C homebrew
    echo >> /home/tanut/.bashrc
    echo 'eval "$(/home/tanut/homebrew/bin/brew shellenv)"' >> /home/tanut/.bashrc
    eval "$(/home/tanut/homebrew/bin/brew shellenv)"

- name: install gcc
  shell: |
    sudo apt update && sudo apt install -y gcc
  become: true

- name: install k9s
  shell: |
    /home/tanut/homebrew/bin/brew install derailed/k9s/k9s