myhosts:
  hosts:
    tanut1:
      ansible_host: 95.217.43.62
    tanut2:
      ansible_host: 88.99.214.157
    # tanut3:
    #   ansible_host: 46.224.9.5
    # tanut4:
    #   ansible_host: 91.98.93.35
    # tanut5:
    #   ansible_host: 46.224.9.3
all:
  vars:
    ansible_user: tanut